version: "3.8"

services:
  configserver:
    image: fseijo/ms_configserver:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
      - bankapplication

  accounts:
    image: fseijo/ms_accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: optional:configserver:http://localhost:8071/
    networks:
      - bankapplication

  loans:
    image: fseijo/ms_loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: optional:configserver:http://localhost:8071/
    networks:
      - bankapplication

  cards:
    image: fseijo/ms_cards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: optional:configserver:http://localhost:8071/
    networks:
      - bankapplication

networks:
  bankapplication: