version: "3.8"

services:
  serverconfig:
    image: fseijo/ms_configserver:latest
    deploy:
      resources:
        limits:
          memory: 700M
    ports:
      - "8073:8071"
    networks:
      - bankapplication-network

  accounts:
    image: fseijo/ms_accounts:latest
    restart: always
    ports:
      - "8087:8080"
    depends_on:
      - serverconfig
    deploy:
      resources:
        limits:
          memory: 700M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      #      SPRING_CONFIG_IMPORT: configserver:http://localhost:8071/
      SPRING_CONFIG_IMPORT: configserver:http://host.docker.internal:8071/
    networks:
      - bankapplication-network

  loans:
    image: fseijo/ms_loans:latest
    restart: always

    ports:
      - "8097:8090"
    depends_on:
      - serverconfig
    deploy:
      resources:
        limits:
          memory: 700M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      #      SPRING_CONFIG_IMPORT: configserver:http://localhost:8071/
      SPRING_CONFIG_IMPORT: configserver:http://host.docker.internal:8071/
    networks:
      - bankapplication-network

  cards:
    image: fseijo/ms_cards:latest
    restart: always
    ports:
      - "9007:9000"
    depends_on:
      - serverconfig
    deploy:
      resources:
        limits:
          memory: 700M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      #      SPRING_CONFIG_IMPORT: configserver:http://localhost:8071/
      SPRING_CONFIG_IMPORT: configserver:http://host.docker.internal:8071/
    networks:
      - bankapplication-network

networks:
  bankapplication-network: